### ISSUE TITLE
Bug when using a bad input in cfg file

### ISSUE THREAD

**Issue by talDoFlemis** [Lu1z-Gust4v0/Fup-Final_Project#49]
Acontece toda vez que no arquivo de config tem um input como
`A,B:5`
Provavelment o erro ta dentro da função parse_input

![image](https://user-images.githubusercontent.com/33133120/174432757-aaa14b8f-75e4-4aa3-aadd-d2f2e54f7125.png)

**Comment by Lu1z-Gust4v0** [comment]
Bug Fixed
