### ISSUE TITLE
Bug when there is a bad input in interactive mode

### ISSUE THREAD

**Issue by talDoFlemis** [Lu1z-Gust4v0/Fup-Final_Project#50]
Acontece toda vez que no modo interativo tem um input como
`A,B:5` ou `A,5:B`
Provavelment o erro ta dentro da função parse_input

![image](https://user-images.githubusercontent.com/33133120/174432757-aaa14b8f-75e4-4aa3-aadd-d2f2e54f7125.png)

**Comment by Lu1z-Gust4v0** [comment]
Bug fixed
