### ISSUE TITLE
Bug when there is a bad input in move file

### ISSUE THREAD

**Issue by talDoFlemis** [Lu1z-Gust4v0/Fup-Final_Project#52]
Mesma coisa que acontece com os outros, provalmente é um bug na fn parse_input quando ela recebe
`A,B:5` ou `A,5:B`

![image](https://user-images.githubusercontent.com/33133120/174433316-050e33bd-b457-4d2b-8992-e2b35b47c5b5.png)

Sugestão: Não sei se existe um try and catch no python, mas é quando a fn tenta converter uma letra em inteiro que ta dando problema

**Comment by Lu1z-Gust4v0** [comment]
bug fixed
