### ISSUE TITLE
Sudoku not ignoring 2 repeted hints

### ISSUE THREAD

**Issue by talDoFlemis** [Lu1z-Gust4v0/Fup-Final_Project#65]
O programa deveria ignorar duas hints repetidas e continuar o processo, mas ele ta dando erro
Com o arquivo de cfg como:
```
A,3:2
A,3:2
```
Ele acusa erro, mesmo ja tendo ajustado a parada do tuple, provavelmente por causa disso aqui
```python
def check_all_moves(grid, target_row, target_col, value):
    valid_hor_ver, hor_ver_mot = check_hor_ver(grid, target_row, target_col, value)
    valid_block, block_mot = check_block(grid, target_row, target_col, value)

    if grid[target_row][target_col]["value"] == value and not is_cell_hint(
        grid, target_row, target_col
    ):
        return True, ""

    if not valid_hor_ver:
        return False, hor_ver_mot

    if not valid_block:
        return False, block_mot

    if is_cell_hint(grid, target_row, target_col):
        return False, "tentando sobrescrever uma dica"

    return True, ""
```

Quando o valor a ser sobrescrito é igual ao anterior e ele **é uma hint** ele não retorna true e continua a parada. Ele continua a execução e vai parar nas de checar o valid_hor ou block, porque vai encontrar uma coluna,linha ou bloco, que contem o mesmo valor que seria sobrescrito.

Sugestão: usar uma flag pra indicar que ta populando o grid com hints.

**Comment by Lu1z-Gust4v0** [comment]
Solved
